### ISSUE TITLE
OSError when running text2pointcloud example

### ISSUE THREAD

**Issue by peruginiandrea** [openai/point-e#12]
`base_model = model_from_config(MODEL_CONFIGS[base_name], device)` in `text2pointcloud.ipynb` causes the error `OSError: [Errno 30] Read-only file system: '/point_e_model_cache'`

Running macOS Ventura 13.2, M1, Python 3.9.13

**Comment by eliecer696** [comment]
i get this error pointcloud.ipynb
Traceback (most recent call last):
  File "C:\\\\\point-e-main\point_e\examples\text2pointcloud.ipynb", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined

**Comment by peruginiandrea** [comment]
UPDATE: I've just found out that it works as expected when running it interactively from the terminal, while the error happens using jupyter notebook
So I assume it's a problem on my end
