### ISSUE TITLE
skimage does not have attribute: measure

### ISSUE THREAD

**Issue by pratos** [openai/point-e#17]
Faced an issue while importing `skimage.measure`. Related to this issue: [scikit-image#4266](https://github.com/scikit-image/scikit-image/issues/4266)

Fix was to update the imports in the file -> [point_e/util/pc_to_mesh.py](https://github.com/openai/point-e/blob/main/point_e/util/pc_to_mesh.py):

- Line no: [link](https://github.com/openai/point-e/blob/fc8a607c08a3ea804cc82bf1ef8628f88a3a5d2f/point_e/util/pc_to_mesh.py#L4)
- From:
```
import skimage
```
- To:
```py
import skimage.measure as skm
```

- `skimage.__version__ == 0.18.3`

**Comment by pratos** [comment]
Putting it here coz did not have push access to create a PR and someone might face this same issue.

**Comment by Andrej730** [comment]
Please leave the issue open - it still persists for anyone who will try to run [pointcloud2mesh.ipynb](https://github.com/openai/point-e/blob/main/point_e/examples/pointcloud2mesh.ipynb):


```[/content/point-e/point_e/util/pc_to_mesh.py](https://localhost:8080/#) in marching_cubes_mesh(pc, model, batch_size, grid_size, side_length, fill_vertex_channels, progress)
     68         volume_np -= np.mean(volume_np)
     69 
---> 70     verts, faces, normals, _ = skimage.measure.marching_cubes(
     71         volume=volume_np,
     72         level=0,
AttributeError: module 'skimage' has no attribute 'measure'
```

PR with solution is #33. I think it needs to be merged.

Other similar PR is #22 but it solves the issue only for the notebook and won't solve it if someone will try to use `marching_cubes_mesh()` outside of the notebook. I think this PR can be closed.

@unixpickle @heewooj
