### ISSUE TITLE
What is the point resolution / density? 

### ISSUE THREAD

**Issue by NewAlexandria** [openai/point-e#30]
It would be great to hear more, at a high level, about limits on the point density.  Is it variable to how features are made and attached?  

Like if I want a living room -> in a house -> on a basketball -> in the hand -> of a person, sitting in an airplane, would there be a variable mesh all the way into that chain?  

Or would some of that just get cut off?  Is it averaged overall to some viewport-concept of the whole object?

**Comment by unixpickle** [comment]
Our current focus is on generating single isolated objects with uniform level-of-detail. The models produce point clouds in two stages: the first has 1024 points, and the second has 4096 points.

**Comment by NewAlexandria** [comment]
ok, so the objects will have a max number of 4096 points regardless of the object, and the points will be roughly evenly distributed across all features?

**Comment by NewAlexandria** [comment]
after that do you think you'll move on to another pass, e.g. for 8 or 16k points?  Or instead deal with compositions / stitching of multiple meshes which each had their own resolution process?
