### ISSUE TITLE
Projecting pixels in the renders (depth maps together with the camera_matrices) generated by blender back to 3d point cloud

### ISSUE THREAD

**Issue by easonnie** [openai/point-e#35]
Thank you so much for sharing the [blender_script](https://github.com/openai/point-e/blob/main/point_e/evals/scripts/blender_script.py) ! I was wondering what is **the version of blender** that is used.

To build own training data, it would be really appreciated if you could share more about how to re-built the 3d point clouds from the renders and camera matrices generated by blender.

**Comment by muzhou-yu** [comment]
> Thank you so much for sharing the [blender_script](https://github.com/openai/point-e/blob/main/point_e/evals/scripts/blender_script.py) ! I was wondering what is **the version of blender** that is used.
> 
> To build own training data, it would be really appreciated if you could share more about how to re-built the 3d point clouds from the renders and camera matrices generated by blender.

Have you solved this problem?

**Comment by zhao-yiqun** [comment]
Hi, @easonnie @muzhou-yu , Have you ever solved the re-built 3d point clouds problem?

**Comment by easonnie** [comment]
Hi @muzhou-yu @zhao-yiqun, I've been working on a project involving 3D textured mesh generation, and we've recently published an initial draft of our findings here: https://arxiv.org/abs/2303.05371. We'll soon be releasing a script that allows for the reconstruction of 3D point clouds from renders, as explained in our paper. Please stay tuned for updates.

**Comment by JinyiW** [comment]
Looking forward to see your solution in 3Dgen!
