### ISSUE TITLE
Process multiple images

### ISSUE THREAD

**Issue by kevincolten** [openai/point-e#61]
Is there a way to process multiple images (at different angles) to generate a more accurate point cloud?

**Comment by mturnshek** [comment]
@kevincolten Did you close because you reached a resolution on your issue?

**Comment by kevincolten** [comment]
Yes, https://gist.github.com/kevincolten/56529dcb4a42ea3e159e76322a9980e6

**Comment by muzhou-yu** [comment]
> Yes, https://gist.github.com/kevincolten/56529dcb4a42ea3e159e76322a9980e6

Can you tell me how to solve this problem? I can not open this link

**Comment by kevincolten** [comment]
@mturnshek The gist link doesn't load?

cc @muzhou-yu

**Comment by mturnshek** [comment]
It loads. Not sure what they’re on about.
