### ISSUE TITLE
Iteration rate drops drastically after 67th iteration

### ISSUE THREAD

**Issue by Teragron** [openai/point-e#9]
Hi, i am trying to run the text2pointcloud script locally. During the first 67 iteration, the speed of the iteration was acceptable but after that the model iterates once every 70-80 seconds. I am testing the model with "corgi.jpg", which worked fine in the colab. 

```
106it [1:08:34, 71.01s/it]
```
GPU: 1660 Ti Max-Q (6 GB VRAM)
Python Version: 3.8.15
Model: base40M

**Comment by unixpickle** [comment]
You are likely seeing that the upsampler (second stage) is much slower than the base model. Not sure why it's soo slow on your hardware though. Will leave this issue open for now.

**Comment by LMSDev** [comment]
I had the exact same issue in the second stage when torch used my CPU by accident. Make sure torch.cuda.is_available() returns true.

**Comment by Teragron** [comment]
> I had the exact same issue in the second stage when torch used my CPU by accident. Make sure torch.cuda.is_available() returns true.

It indeed returned False. After installing Pytorch for CUDA 11.7 i got 2 iterations per second. Thanks!
