### ISSUE TITLE
Return Points with simple API Request?

### ISSUE THREAD

**Issue by Mashimaro7** [openai/point-e#96]
I can't find anything about this, but is there a way to just generate a model with an API call with Point E? I want to make a basic object generator with Unity, and the only guides i can find are for how to use it in Python. I imagine there's some way to just send an API request and return the model's info? Or does anyone know of an alternate way to get it working in Unity?

Thanks

**Comment by moonlockwood** [comment]
This is a local model that runs on your gpu, not an api, I hope that helps! Can be daunting at first, but once a good python environment is set up you can get models with just a few lines of python.

**Comment by Mashimaro7** [comment]
@moonlburger  Oh, thanks for the reply. I found out Replicate has an API hosted already
